name: Handle Prohibited Word Notification

on:
  repository_dispatch:
    types: [prohibited-word-found]

jobs:
  handle-prohibited-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B code
        uses: actions/checkout@v3

      - name: Notify about Prohibited Word
        run: |
          echo "A prohibited word was found in PR from Repo A: ${{ github.event.client_payload.pr_url }}"
          # Add other actions here, like commenting on the PR, notifying team members, etc.
