name: Handle Prohibited Word Notification
inputs:
  message:  # id of input
  description: 'What is the message? '
  required: true
  default: 'World'
outputs:
  random-number:
  description: "Random number"
  value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello ."
    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo "11")" >> $GITHUB_OUTPUT
