name: Workflow 2 - Pass PR Details to Workflow 3

on:
  workflow_call:

jobs:
  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PR details
        id: pr_details
        run: |
          echo "pr_title=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "pr_url=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          echo "pr_author=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

      - name: Pass PR Details to Workflow 3 in Another Repo
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: OSrivalli/reactions  # Replace with the third repo
          workflow: scan.yml
          ref: main  # or the default branch of the third repo
