name: Workflow 2 - Pass PR Details to Workflow 3

on:
  workflow_call:

jobs:
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PR details
        id: pr_details
        run: |
          echo "pr_title=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "pr_url=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          echo "pr_author=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

  job4:
    needs:
      - job3
    uses: OSrivalli/reactions/scan@main


 
