name: Workflow 2 - Pass PR Details to Workflow 3

on:
  workflow_call:

jobs:
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PR details
        id: pr_details
        run: |
          echo "pr_details=${{ github.event.pull_request.* }}" >> $GITHUB_ENV

      - name: Run action
        uses: OSrivalli/reactions@main
        with:
          token: ${{ secrets.PAT_TOKEN }}
          pr_details: ${{ env.pr_title }} 
        


 
