name: Workflow 2 - Pass PR Details to Workflow 3

on:
  repository_dispatch:
    types: [pr-details]

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pass PR details to Workflow 3
        uses: peter-evans/dispatch-action@v2
        with:
          repository: OSrivalli/reactions
          event-type: pr-details
          client-payload: '{"pr_number": "${{ github.event.client_payload.pr_number }}", "pr_title": "${{ github.event.client_payload.pr_title }}", "pr_url": "${{ github.event.client_payload.pr_url }}"}'
          

